prometheus.remote_write "local" {
  endpoint {
    url = "https://${LOGSHIP_HOST}:${LOGSHIP_PORT}/prometheus/api/v1/write"
    basic_auth {
      username = "${LOGSHIP_USERNAME}"
      password = "${LOGSHIP_PASSWORD}"
    }
    tls_config {
      insecure_skip_verify = true
    }
  }
}

prometheus.exporter.unix "local_system" {
  include_exporter_metrics = true
  disable_collectors = ["mdadm"]
}

prometheus.scrape "system_metrics" {
  targets    = prometheus.exporter.unix.local_system.targets
  forward_to = [prometheus.remote_write.local.receiver]
  scrape_interval = "10s"
}


loki.write "default" {
  endpoint {
    url = "https://${LOGSHIP_HOST}:${LOGSHIP_PORT}/loki/api/v1/push"
    basic_auth {
      username = "${LOGSHIP_USERNAME}"
      password = "${LOGSHIP_PASSWORD}"
    }
    tls_config {
      insecure_skip_verify = true
    }
  }
}

local.file_match "docker_logs" {
  path_targets = [
    {
      path   = "/var/lib/docker/containers/*/*.log",
      labels = {
        job = "docker",
      },
    },
  ]
}

loki.source.file "docker_source" {
  targets    = local.file_match.docker_logs.targets
  forward_to = [loki.process.docker_logs.receiver]
}

loki.process "docker_logs" {
  forward_to = [loki.write.default.receiver]
  stage.docker {}
}