services:
  logship_alloy:
    image: grafana/alloy:latest
    network_mode: host
    pid: host
    environment:
      - LOGSHIP_SOURCE={{.Node.Hostname}}
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host/root:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./alloy.${@NAMETAG}.yaml:/etc/alloy/config.alloy
    command:
      - "run"
      - "--storage.path=/var/lib/alloy/data"
      - "/etc/alloy/config.alloy"