
volumes:
  logship_loki:
    driver: local
  logship_prometheus:
    driver: local

services:
  logship_loki:
    mem_limit: 1g
    restart: always
    logging:
      driver: "local"
    image: grafana/loki:3.5
    volumes:
      - ./config.${@NAMETAG}.server.loki.yml:/etc/loki/local-config.yml
      - logship_loki:/loki
    command:
      - '-config.file=/etc/loki/local-config.yml'

  logship_prometheus:
    mem_limit: 1g
    restart: always
    logging:
      driver: "local"
    image: prom/prometheus:v3.4.0
    volumes:
      - ./config.${@NAMETAG}.server.prometheus.yml:/etc/prometheus/prometheus.yml
      - logship_prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-remote-write-receiver'
      - '--web.enable-lifecycle'