services:
  logship_docker_logs:
    image: grafana/alloy:v1.8.1
    restart: always
    env_file:
      - ./.${@ALIAS}.${@NAMETAG}.env
    volumes:
      - ./config.${@NAMETAG}.docker.logs.alloy:/etc/alloy/config.alloy
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - "run"
      - "--storage.path=/var/lib/alloy/data"
      - "/etc/alloy/config.alloy"

  logship_docker_metrics:
    image: grafana/alloy:v1.8.1
    restart: always
    pid: host
    env_file:
      - ./.${@ALIAS}.${@NAMETAG}.env
    volumes:
      - ./config.${@NAMETAG}.docker.metrics.alloy:/etc/alloy/config.alloy
      - /proc:/proc
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - "run"
      - "--storage.path=/var/lib/alloy/data"
      - "/etc/alloy/config.alloy"

  logship_system_logs:
    image: grafana/alloy:v1.8.1
    restart: always
    env_file:
      - ./.${@ALIAS}.${@NAMETAG}.env
    volumes:
      - ./config.${@NAMETAG}.system.logs.alloy:/etc/alloy/config.alloy
      - /var/log:/host/var/log:ro
    command:
      - "run"
      - "--storage.path=/var/lib/alloy/data"
      - "/etc/alloy/config.alloy"

  logship_system_metrics:
    image: grafana/alloy:v1.8.1
    pid: host
    restart: always
    env_file:
      - ./.${@ALIAS}.${@NAMETAG}.env
    volumes:
      - ./config.${@NAMETAG}.system.metrics.alloy:/etc/alloy/config.alloy
      - /proc:/proc
      - /sys:/sys:ro
    command:
      - "run"
      - "--storage.path=/var/lib/alloy/data"
      - "/etc/alloy/config.alloy"