import fs from 'fs'
import { getGraphqlRouterConfigs, getGraphqlModules, createGraphqlResovlerFile } from '@ts.app/core/common/cli/util.js'
import { TypeStack, CWD } from '@ts.app/core/common/cli/typestack.js'
import { generate } from '@graphql-codegen/cli'
import { Types } from '@graphql-codegen/plugin-helpers'

export type GraphqlOptions = {
    cwd: CWD
}

export const graphql = async (options: GraphqlOptions) => {
    const ts = await TypeStack.getConfig()
    const cwd = ts.cwd
    const packages = ts.packages
    const entry = ts.entrypoint

    // initilize graphql/resolvers.json file
    createGraphqlResovlerFile(ts)

    const scalars = {
        Object: '{[key:string]: any}',
        DateTime: 'Date',
        Packages: 'string',
        ObjectId: 'MongooseTypes.ObjectId',
    }

    for (const graphql_server of await getGraphqlRouterConfigs(ts)) {
        var {schema} = await getGraphqlModules(graphql_server, {schema: true, resolvers: false})

        // if schema is empty
        if(!schema || schema == "" || schema.length == 0){
            console.log(`skipping, empty schema for pack:${graphql_server.pack} name:${graphql_server.name}`)
            continue
        }

        const generates: Types.Config['generates'] = {}

        generates[graphql_server.typeDefPath] = {
            plugins: ['typescript', 'typescript-operations', 'typescript-resolvers', 'typed-document-node' ],
            config: {
                typesPrefix: 'I',
                declarationKind: 'interface',
                scalars: scalars,
                enumsAsTypes: true,
                skipTypename: true,
            }
        } satisfies Types.ConfiguredOutput | Types.ConfiguredPlugin[]

        if(graphql_server.genClient == true) {
            generates[graphql_server.clientPath] = {
                preset: 'client',
                config: { scalars: scalars }
            } satisfies Types.ConfiguredOutput | Types.ConfiguredPlugin[]
        }

        // write schema to file
        const CodegenConfig: Types.Config = {
            errorsOnly: true,
            debug: true,
            verbose: false,
            schema,
            documents: graphql_server.documents,
            generates
        }

        

        const template = (client: boolean, file_result: string) => `
            import type { DeepRequired } from 'utility-types'
            import type { Types as MongooseTypes } from 'mongoose'
            ` + (client ? `import type { IResolvers, IGraphqlMethod, IAccessOptions } from '${graphql_server.pack}/codegen/${graphql_server.name}/index.js'` : '') + `
            

            ${file_result}

            // additional types generated by build-graphql.js script!
            export type GraphqlResolvers = Record<IGraphqlMethod, Record<string, any>>

            export type GraphObj = Scalars["Object"]["input"]

            type GraphqlResources<T extends GraphqlResolvers> = {
                [K in IGraphqlMethod]?: {
                    [K2 in keyof T[K]]?: IAccessOptions  
                } 
            }

            export type Resources<T> = GraphqlResources<DeepRequired<IResolvers<T>>>
        `

        try {
            // if graphql shema is empty
            if(!CodegenConfig.schema || CodegenConfig.schema == "") throw new Error('graphql schema is empty')
            // generate graphql code
            await generate(CodegenConfig, true)
            const file_result = fs.readFileSync(graphql_server.typeDefPath, 'utf8')
            fs.writeFileSync(graphql_server.typeDefPath, template(false, file_result), 'utf8')

            const clientFile = `${graphql_server.clientPath}/graphql.ts`
            if(graphql_server.genClient == true && fs.existsSync(clientFile)){
                const file_result = fs.readFileSync(clientFile, 'utf8')
                fs.writeFileSync(clientFile, template(true, file_result), 'utf8')
            }
        } catch (error) {
            console.error(error)
            // console.log({...CodegenConfig, schema: '...'})
        }
    }

    // initilize or replace graphql/resolvers.json file
    createGraphqlResovlerFile(ts)
}