// DO NOT EDIT THIS FILE!
// This file is auto generated by 'ts config' cli command
import React from 'react'
import dynamic from 'next/dynamic'
export const apps = [{
    alias: "core",
    pack: "@ts.app/core",
    resource: "User",
    action: "AccountApp",
    admin: {
        hash: "623f6b5618b3ccc14e3eaedeeb8a04156ddbd172c996053a2f7385d9f7a2fd2a",
        app: dynamic(() => import("@ts.app/core/components/apps/AccountApp.js"), {
            ssr: false,
            loading: () => <p>loading...</p>
        }),
        iframe: undefined,
        title: "Account",
        icon: undefined
    }
},{
    alias: "core",
    pack: "@ts.app/core",
    resource: "ApiKey",
    action: "ApiKeyApp",
    admin: {
        hash: "e4389c37be5620c3b3e15f8b6e248859e03c0219026a8edb1ab6101ea93c86bf",
        app: dynamic(() => import("@ts.app/core/components/apps/ApiKeyApp.js"), {
            ssr: false,
            loading: () => <p>loading...</p>
        }),
        iframe: undefined,
        title: "API Keys",
        icon: undefined
    }
},{
    alias: "core",
    pack: "@ts.app/core",
    resource: "RoleConfig",
    action: "RoleApp",
    admin: {
        hash: "bd3b7703664296d4324e69f23cb32ceaa3fa91d6b6b15e3bfdaac99b6754d724",
        app: dynamic(() => import("@ts.app/core/components/apps/RoleApp.js"), {
            ssr: false,
            loading: () => <p>loading...</p>
        }),
        iframe: undefined,
        title: "Roles",
        icon: undefined
    }
},{
    alias: "dev",
    pack: "@ts.app/dev",
    resource: "Test",
    action: "DevApp",
    admin: {
        hash: "a4db4ea3598801ff9f434e6524a2a2c2dad6c9afa28df1dd792558d351565325",
        app: dynamic(() => import("@ts.app/dev/next/app/test/page.js"), {
            ssr: false,
            loading: () => <p>loading...</p>
        }),
        iframe: undefined,
        title: "Dev App",
        icon: undefined
    }
},{
    alias: "dev",
    pack: "@ts.app/dev",
    resource: "Test",
    action: "DevIframe1",
    admin: {
        hash: "c8dfa667360b9b5afab1d388d146007d9386ed1dfef813aea6127d38b00e2bcc",
        app: undefined,
        iframe: ":7443/admin",
        title: "Dev Iframe 1",
        icon: undefined
    }
},{
    alias: "dev",
    pack: "@ts.app/dev",
    resource: "Test",
    action: "DevIframe2",
    admin: {
        hash: "189dc3db594fdf2c845783c34f7e696a8ee2fe98dc708559c01a395b8beb1fbd",
        app: undefined,
        iframe: "https://localhost:7443/admin",
        title: "Dev Iframe 2",
        icon: undefined
    }
},{
    alias: "dev",
    pack: "@ts.app/dev",
    resource: "Test",
    action: "DevIframe3",
    admin: {
        hash: "a362d38510392856f9cedd4f87800134f8e0ee33c5c65240fa65dcbd53698e8a",
        app: undefined,
        iframe: "/admin",
        title: "Dev Iframe 3",
        icon: undefined
    }
}]